<?php
/**
 * TokenTimestamp
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * speechapi
 *
 * Speech APIs enable you to recognize speech and convert it to text using advanced machine learning, and also to convert text to speech.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * TokenTimestamp Class Doc Comment
 *
 * @category Class
 * @description A single token with its time range and position in the output text
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TokenTimestamp implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'TokenTimestamp';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'token' => 'string',
        'character_offset_start' => 'int',
        'character_offset_end' => 'int',
        'start_time_ms' => 'int',
        'end_time_ms' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'token' => null,
        'character_offset_start' => 'int32',
        'character_offset_end' => 'int32',
        'start_time_ms' => 'int64',
        'end_time_ms' => 'int64'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'token' => 'Token',
        'character_offset_start' => 'CharacterOffsetStart',
        'character_offset_end' => 'CharacterOffsetEnd',
        'start_time_ms' => 'StartTimeMs',
        'end_time_ms' => 'EndTimeMs'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'token' => 'setToken',
        'character_offset_start' => 'setCharacterOffsetStart',
        'character_offset_end' => 'setCharacterOffsetEnd',
        'start_time_ms' => 'setStartTimeMs',
        'end_time_ms' => 'setEndTimeMs'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'token' => 'getToken',
        'character_offset_start' => 'getCharacterOffsetStart',
        'character_offset_end' => 'getCharacterOffsetEnd',
        'start_time_ms' => 'getStartTimeMs',
        'end_time_ms' => 'getEndTimeMs'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['token'] = isset($data['token']) ? $data['token'] : null;
        $this->container['character_offset_start'] = isset($data['character_offset_start']) ? $data['character_offset_start'] : null;
        $this->container['character_offset_end'] = isset($data['character_offset_end']) ? $data['character_offset_end'] : null;
        $this->container['start_time_ms'] = isset($data['start_time_ms']) ? $data['start_time_ms'] : null;
        $this->container['end_time_ms'] = isset($data['end_time_ms']) ? $data['end_time_ms'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets token
     *
     * @return string
     */
    public function getToken()
    {
        return $this->container['token'];
    }

    /**
     * Sets token
     *
     * @param string $token The token text (word or subword)
     *
     * @return $this
     */
    public function setToken($token)
    {
        $this->container['token'] = $token;

        return $this;
    }

    /**
     * Gets character_offset_start
     *
     * @return int
     */
    public function getCharacterOffsetStart()
    {
        return $this->container['character_offset_start'];
    }

    /**
     * Sets character_offset_start
     *
     * @param int $character_offset_start Start character offset (0-based) in TextResult
     *
     * @return $this
     */
    public function setCharacterOffsetStart($character_offset_start)
    {
        $this->container['character_offset_start'] = $character_offset_start;

        return $this;
    }

    /**
     * Gets character_offset_end
     *
     * @return int
     */
    public function getCharacterOffsetEnd()
    {
        return $this->container['character_offset_end'];
    }

    /**
     * Sets character_offset_end
     *
     * @param int $character_offset_end End character offset (exclusive) in TextResult
     *
     * @return $this
     */
    public function setCharacterOffsetEnd($character_offset_end)
    {
        $this->container['character_offset_end'] = $character_offset_end;

        return $this;
    }

    /**
     * Gets start_time_ms
     *
     * @return int
     */
    public function getStartTimeMs()
    {
        return $this->container['start_time_ms'];
    }

    /**
     * Sets start_time_ms
     *
     * @param int $start_time_ms Start time of this token in the audio, in milliseconds
     *
     * @return $this
     */
    public function setStartTimeMs($start_time_ms)
    {
        $this->container['start_time_ms'] = $start_time_ms;

        return $this;
    }

    /**
     * Gets end_time_ms
     *
     * @return int
     */
    public function getEndTimeMs()
    {
        return $this->container['end_time_ms'];
    }

    /**
     * Sets end_time_ms
     *
     * @param int $end_time_ms End time of this token in the audio, in milliseconds
     *
     * @return $this
     */
    public function setEndTimeMs($end_time_ms)
    {
        $this->container['end_time_ms'] = $end_time_ms;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


