<?php
/**
 * TokenTimestampTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * speechapi
 *
 * Speech APIs enable you to recognize speech and convert it to text using advanced machine learning, and also to convert text to speech.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.5
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TokenTimestampTest Class Doc Comment
 *
 * @category    Class
 * @description A single token with its time range and position in the output text
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TokenTimestampTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TokenTimestamp"
     */
    public function testTokenTimestamp()
    {
    }

    /**
     * Test attribute "token"
     */
    public function testPropertyToken()
    {
    }

    /**
     * Test attribute "character_offset_start"
     */
    public function testPropertyCharacterOffsetStart()
    {
    }

    /**
     * Test attribute "character_offset_end"
     */
    public function testPropertyCharacterOffsetEnd()
    {
    }

    /**
     * Test attribute "start_time_ms"
     */
    public function testPropertyStartTimeMs()
    {
    }

    /**
     * Test attribute "end_time_ms"
     */
    public function testPropertyEndTimeMs()
    {
    }
}
